name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log Version
        run: |
          node -v
          cat /etc/os-release
      - name: Step with Docker
        uses: docker://node:13.5.0-alpine3.10
        with:
          entrypoint: /bin/echo #path to the executable
          args: Hello World #args to the executable
      - name: Log node version of the container
        uses: docker://node:13.5.0-alpine3.10
        with:
          entrypoint: /usr/local/bin/node #path to the executable
          args: -v #args to the executable
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: Node Version
        run: |
          node -v
          cat /etc/os-release
  mutliple-docker-images:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a request
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\":\"Hello\",\"address\":\"sdad\"}'"
      - name: Get User
        run: "curl http://localhost:3001/api/users"