name: Custom Action Test
on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: Issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: title
          body: Body
          assignees: |
            SanjaySaatyaki
      - run: |
          echo ${{steps.Issues.outputs.issue}}
      - uses: ./.github/actions/hello
        id: Hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{steps.Hello.outputs.time}}"
          echo $Hello

