name: Test Environment Variables

on:
  workflow_dispatch:

env:
  WF_ENV: Global Env
  MYTOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  exec_pyhon:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: installion
        run: pip install actions_toolkit
      - name: Execute python
        run: |
          python schedule.py
